/**
 * _lib.mjs — shared helpers for the Octo docs SSOT generators
 * (gen-api.mjs, gen-cli.mjs, gen-config.mjs). Emits Mintlify MDX. See DESIGN.md §6.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** octo-docs repo root. */
export const DOCS_ROOT = path.resolve(__dirname, '..');
/** Parent dir holding the sibling repos (octo-cli, octo-auth, octo-server, …). */
export const WORKSPACE = path.resolve(DOCS_ROOT, '..');

export const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'];

export const RISK_BADGE = {
  read: '🟢 read',
  write: '🟠 write',
  'high-risk-write': '🔴 high-risk',
};

/** DO-NOT-EDIT banner (MDX comment) pointing back at the source of truth. */
export const banner = (source) =>
  `{/*
  DO NOT EDIT — generated by scripts/${source.generator} from the source of truth:
  ${source.spec}
  Run \`npm run gen:all\` after changing the spec. See DESIGN.md §6.
*/}`;

/** Resolve a local $ref (#/components/...) against the root document. */
export function deref(node, root, seen = new Set()) {
  if (!node || typeof node !== 'object') return node;
  if (typeof node.$ref === 'string' && node.$ref.startsWith('#/')) {
    if (seen.has(node.$ref)) return {};
    seen.add(node.$ref);
    const target = node.$ref
      .slice(2)
      .split('/')
      .reduce((acc, key) => (acc ? acc[decodeURIComponent(key)] : undefined), root);
    return deref(target, root, seen);
  }
  return node;
}

/** Escape a string for safe inline use in an MDX table cell / paragraph. */
export function mdEscape(s) {
  return String(s ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\n+/g, ' ')
    // Wrap bare URLs in backticks so MDX doesn't try to auto-link them.
    .replace(/https?:\/\/[^\s`）)]+/g, (u) => `\`${u}\``)
    // Neutralise MDX hazards: {expr} and <tag> in prose.
    .replace(/[<>{}]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '{': '&#123;', '}': '&#125;' }[c]))
    .trim();
}

/** Escape a value that will be wrapped in inline code (backticks). */
export function codeEscape(s) {
  return String(s ?? '').replace(/\|/g, '\\|').trim();
}

/** Human-readable type label for an OpenAPI schema. */
export function typeOf(schema) {
  if (!schema) return '—';
  if (schema.type === 'array' && schema.items) return `${typeOf(schema.items)}[]`;
  if (schema.enum) return `enum(${schema.enum.map((e) => `\`${e}\``).join(', ')})`;
  return schema.type || (schema.properties ? 'object' : '—');
}

export function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/**
 * Render an object schema's top-level properties as a Markdown table.
 * `labels` provides the (translatable) header cells.
 */
export function propsTable(schema, root, labels) {
  schema = deref(schema, root);
  if (!schema || !schema.properties) return '';
  const required = new Set(schema.required || []);
  const rows = Object.entries(schema.properties).map(([name, raw]) => {
    const p = deref(raw, root);
    return `| \`${name}\` | ${typeOf(p)} | ${required.has(name) ? '✓' : ''} | ${mdEscape(p.description)} |`;
  });
  if (!rows.length) return '';
  return `| ${labels.field} | ${labels.type} | ${labels.required} | ${labels.desc} |\n|---|---|---|---|\n` + rows.join('\n');
}

/**
 * A write sink that supports --check (drift detection) mode.
 */
export function createSink({ check = false, generator = 'gen' } = {}) {
  const drift = [];
  return {
    emit(file, content) {
      const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
      if (prev === content) return;
      if (check) {
        drift.push(path.relative(DOCS_ROOT, file));
        return;
      }
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    },
    finish(okMessage) {
      if (check) {
        if (drift.length) {
          console.error(`[${generator}] OUT OF DATE — run \`npm run gen:all\`:`);
          drift.forEach((f) => console.error('  - ' + f));
          return false;
        }
        console.log(`[${generator}] up to date ✓`);
        return true;
      }
      console.log(okMessage);
      return true;
    },
  };
}
